import { CSSVariablesResolver } from "@mantine/core";
import {
  DefaultDarkOne,
  DefaultDarkTwo,
  DefaultDarkThree,
  DefaultDarkFour,
  DefaultDarkFive,
  DefaultDarkBorder,
  DefaultLightOne,
  DefaultLightTwo,
  DefaultLightThree,
  DefaultLightFour,
  DefaultLightFive,
  DefaultLightBorder,
  RedDarkOne,
  RedDarkTwo,
  RedDarkThree,
  RedDarkFour,
  RedDarkFive,
  RedLightOne,
  RedLightTwo,
  RedLightThree,
  RedLightFour,
  RedLightFive,
  PinkDarkOne,
  PinkDarkTwo,
  PinkDarkThree,
  PinkDarkFour,
  PinkDarkFive,
  PinkLightOne,
  PinkLightTwo,
  PinkLightThree,
  PinkLightFour,
  PinkLightFive,
  GrapeDarkOne,
  GrapeDarkTwo,
  GrapeDarkThree,
  GrapeDarkFour,
  GrapeDarkFive,
  GrapeLightOne,
  GrapeLightTwo,
  GrapeLightThree,
  GrapeLightFour,
  GrapeLightFive,
  VioletDarkOne,
  VioletDarkTwo,
  VioletDarkThree,
  VioletDarkFour,
  VioletDarkFive,
  VioletLightOne,
  VioletLightTwo,
  VioletLightThree,
  VioletLightFour,
  VioletLightFive,
  IndigoDarkOne,
  IndigoDarkTwo,
  IndigoDarkThree,
  IndigoDarkFour,
  IndigoDarkFive,
  IndigoLightOne,
  IndigoLightTwo,
  IndigoLightThree,
  IndigoLightFour,
  IndigoLightFive,
  BlueDarkOne,
  BlueDarkTwo,
  BlueDarkThree,
  BlueDarkFour,
  BlueDarkFive,
  BlueLightOne,
  BlueLightTwo,
  BlueLightThree,
  BlueLightFour,
  BlueLightFive,
  CyanDarkOne,
  CyanDarkTwo,
  CyanDarkThree,
  CyanDarkFour,
  CyanDarkFive,
  CyanLightOne,
  CyanLightTwo,
  CyanLightThree,
  CyanLightFour,
  CyanLightFive,
  TealDarkOne,
  TealDarkTwo,
  TealDarkThree,
  TealDarkFour,
  TealDarkFive,
  TealLightOne,
  TealLightTwo,
  TealLightThree,
  TealLightFour,
  TealLightFive,
  GreenDarkOne,
  GreenDarkTwo,
  GreenDarkThree,
  GreenDarkFour,
  GreenDarkFive,
  GreenLightOne,
  GreenLightTwo,
  GreenLightThree,
  GreenLightFour,
  GreenLightFive,
  LimeDarkOne,
  LimeDarkTwo,
  LimeDarkThree,
  LimeDarkFour,
  LimeDarkFive,
  LimeLightOne,
  LimeLightTwo,
  LimeLightThree,
  LimeLightFour,
  LimeLightFive,
  YellowDarkOne,
  YellowDarkTwo,
  YellowDarkThree,
  YellowDarkFour,
  YellowDarkFive,
  YellowLightOne,
  YellowLightTwo,
  YellowLightThree,
  YellowLightFour,
  YellowLightFive,
  OrangeDarkOne,
  OrangeDarkTwo,
  OrangeDarkThree,
  OrangeDarkFour,
  OrangeDarkFive,
  OrangeLightOne,
  OrangeLightTwo,
  OrangeLightThree,
  OrangeLightFour,
  OrangeLightFive,
} from "./color.styles";

export const resolveCssVariables: CSSVariablesResolver = () => cssVariables();

export const cssVariables = () => {
  return {
    variables: {
      "--theme-default": "#696969",
      "--theme-red": "#c92a2a",
      "--theme-pink": "#a61e4d",
      "--theme-grape": "#862e9c",
      "--theme-violet": "#5f3dc4",
      "--theme-indigo": "#364fc7",
      "--theme-blue": "#1864ab",
      "--theme-cyan": "#0b7285",
      "--theme-teal": "#087f5b",
      "--theme-green": "#2b8a3e",
      "--theme-lime": "#5c940d",
      "--theme-yellow": "#DAA520",
      "--theme-orange": "#d9480f",
    },
    light: {
      "--primary-text": DefaultDarkOne,
      "--primary-background": DefaultLightOne,
      "--secondary-text": DefaultDarkTwo,
      "--secondary-background": DefaultLightTwo,
      "--tertiary-text": DefaultDarkThree,
      "--tertiary-background": DefaultLightThree,
      "--quaternary-text": DefaultDarkFour,
      "--quaternary-background": DefaultLightFour,
      "--quinary-text": DefaultDarkFive,
      "--quinary-background": DefaultLightFive,
      "--border-low-contrast": DefaultLightBorder,
      "--border-high-contrast": DefaultDarkBorder,
      "--primary-red-text": RedDarkOne,
      "--primary-red-background": RedLightOne,
      "--secondary-red-text": RedDarkTwo,
      "--secondary-red-background": RedLightTwo,
      "--tertiary-red-text": RedDarkThree,
      "--tertiary-red-background": RedLightThree,
      "--quaternary-red-text": RedDarkFour,
      "--quaternary-red-background": RedLightFour,
      "--quinary-red-text": RedDarkFive,
      "--quinary-red-background": RedLightFive,
      "--primary-pink-text": PinkDarkOne,
      "--primary-pink-background": PinkLightOne,
      "--secondary-pink-text": PinkDarkTwo,
      "--secondary-pink-background": PinkLightTwo,
      "--tertiary-pink-text": PinkDarkThree,
      "--tertiary-pink-background": PinkLightThree,
      "--quaternary-pink-text": PinkDarkFour,
      "--quaternary-pink-background": PinkLightFour,
      "--quinary-pink-text": PinkDarkFive,
      "--quinary-pink-background": PinkLightFive,
      "--primary-grape-text": GrapeDarkOne,
      "--primary-grape-background": GrapeLightOne,
      "--secondary-grape-text": GrapeDarkTwo,
      "--secondary-grape-background": GrapeLightTwo,
      "--tertiary-grape-text": GrapeDarkThree,
      "--tertiary-grape-background": GrapeLightThree,
      "--quaternary-grape-text": GrapeDarkFour,
      "--quaternary-grape-background": GrapeLightFour,
      "--quinary-grape-text": GrapeDarkFive,
      "--quinary-grape-background": GrapeLightFive,
      "--primary-violet-text": VioletDarkOne,
      "--primary-violet-background": VioletLightOne,
      "--secondary-violet-text": VioletDarkTwo,
      "--secondary-violet-background": VioletLightTwo,
      "--tertiary-violet-text": VioletDarkThree,
      "--tertiary-violet-background": VioletLightThree,
      "--quaternary-violet-text": VioletDarkFour,
      "--quaternary-violet-background": VioletLightFour,
      "--quinary-violet-text": VioletDarkFive,
      "--quinary-violet-background": VioletLightFive,
      "--primary-indigo-text": IndigoDarkOne,
      "--primary-indigo-background": IndigoLightOne,
      "--secondary-indigo-text": IndigoDarkTwo,
      "--secondary-indigo-background": IndigoLightTwo,
      "--tertiary-indigo-text": IndigoDarkThree,
      "--tertiary-indigo-background": IndigoLightThree,
      "--quaternary-indigo-text": IndigoDarkFour,
      "--quaternary-indigo-background": IndigoLightFour,
      "--quinary-indigo-text": IndigoDarkFive,
      "--quinary-indigo-background": IndigoLightFive,
      "--primary-blue-text": BlueDarkOne,
      "--primary-blue-background": BlueLightOne,
      "--secondary-blue-text": BlueDarkTwo,
      "--secondary-blue-background": BlueLightTwo,
      "--tertiary-blue-text": BlueDarkThree,
      "--tertiary-blue-background": BlueLightThree,
      "--quaternary-blue-text": BlueDarkFour,
      "--quaternary-blue-background": BlueLightFour,
      "--quinary-blue-text": BlueDarkFive,
      "--quinary-blue-background": BlueLightFive,
      "--primary-cyan-text": CyanDarkOne,
      "--primary-cyan-background": CyanLightOne,
      "--secondary-cyan-text": CyanDarkTwo,
      "--secondary-cyan-background": CyanLightTwo,
      "--tertiary-cyan-text": CyanDarkThree,
      "--tertiary-cyan-background": CyanLightThree,
      "--quaternary-cyan-text": CyanDarkFour,
      "--quaternary-cyan-background": CyanLightFour,
      "--quinary-cyan-text": CyanDarkFive,
      "--quinary-cyan-background": CyanLightFive,
      "--primary-teal-text": TealDarkOne,
      "--primary-teal-background": TealLightOne,
      "--secondary-teal-text": TealDarkTwo,
      "--secondary-teal-background": TealLightTwo,
      "--tertiary-teal-text": TealDarkThree,
      "--tertiary-teal-background": TealLightThree,
      "--quaternary-teal-text": TealDarkFour,
      "--quaternary-teal-background": TealLightFour,
      "--quinary-teal-text": TealDarkFive,
      "--quinary-teal-background": TealLightFive,
      "--primary-green-text": GreenDarkOne,
      "--primary-green-background": GreenLightOne,
      "--secondary-green-text": GreenDarkTwo,
      "--secondary-green-background": GreenLightTwo,
      "--tertiary-green-text": GreenDarkThree,
      "--tertiary-green-background": GreenLightThree,
      "--quaternary-green-text": GreenDarkFour,
      "--quaternary-green-background": GreenLightFour,
      "--quinary-green-text": GreenDarkFive,
      "--quinary-green-background": GreenLightFive,
      "--primary-lime-text": LimeDarkOne,
      "--primary-lime-background": LimeLightOne,
      "--secondary-lime-text": LimeDarkTwo,
      "--secondary-lime-background": LimeLightTwo,
      "--tertiary-lime-text": LimeDarkThree,
      "--tertiary-lime-background": LimeLightThree,
      "--quaternary-lime-text": LimeDarkFour,
      "--quaternary-lime-background": LimeLightFour,
      "--quinary-lime-text": LimeDarkFive,
      "--quinary-lime-background": LimeLightFive,
      "--primary-yellow-text": YellowDarkOne,
      "--primary-yellow-background": YellowLightOne,
      "--secondary-yellow-text": YellowDarkTwo,
      "--secondary-yellow-background": YellowLightTwo,
      "--tertiary-yellow-text": YellowDarkThree,
      "--tertiary-yellow-background": YellowLightThree,
      "--quaternary-yellow-text": YellowDarkFour,
      "--quaternary-yellow-background": YellowLightFour,
      "--quinary-yellow-text": YellowDarkFive,
      "--quinary-yellow-background": YellowLightFive,
      "--primary-orange-text": OrangeDarkOne,
      "--primary-orange-background": OrangeLightOne,
      "--secondary-orange-text": OrangeDarkTwo,
      "--secondary-orange-background": OrangeLightTwo,
      "--tertiary-orange-text": OrangeDarkThree,
      "--tertiary-orange-background": OrangeLightThree,
      "--quaternary-orange-text": OrangeDarkFour,
      "--quaternary-orange-background": OrangeLightFour,
      "--quinary-orange-text": OrangeDarkFive,
      "--quinary-orange-background": OrangeLightFive,
      "--theme-default-bg": DefaultLightFive,
      "--theme-red-bg": RedLightFive,
      "--theme-pink-bg": PinkLightFive,
      "--theme-grape-bg": GrapeLightFive,
      "--theme-violet-bg": VioletLightFive,
      "--theme-indigo-bg": IndigoLightFive,
      "--theme-blue-bg": BlueLightFive,
      "--theme-cyan-bg": CyanLightFive,
      "--theme-teal-bg": TealLightFive,
      "--theme-green-bg": GreenLightFive,
      "--theme-lime-bg": LimeLightFive,
      "--theme-yellow-bg": YellowLightFive,
      "--theme-orange-bg": OrangeLightFive,
    },
    dark: {
      "--primary-text": DefaultLightOne,
      "--primary-background": DefaultDarkOne,
      "--secondary-text": DefaultLightTwo,
      "--secondary-background": DefaultDarkTwo,
      "--tertiary-text": DefaultLightThree,
      "--tertiary-background": DefaultDarkThree,
      "--quaternary-text": DefaultLightFour,
      "--quaternary-background": DefaultDarkFour,
      "--quinary-text": DefaultLightFive,
      "--quinary-background": DefaultDarkFive,
      "--border-low-contrast": DefaultDarkBorder,
      "--border-high-contrast": DefaultLightBorder,
      "--primary-red-text": RedLightOne,
      "--primary-red-background": RedDarkOne,
      "--secondary-red-text": RedLightTwo,
      "--secondary-red-background": RedDarkTwo,
      "--tertiary-red-text": RedLightThree,
      "--tertiary-red-background": RedDarkThree,
      "--quaternary-red-text": RedLightFour,
      "--quaternary-red-background": RedDarkFour,
      "--quinary-red-text": RedLightFive,
      "--quinary-red-background": RedDarkFive,
      "--primary-pink-text": PinkLightOne,
      "--primary-pink-background": PinkDarkOne,
      "--secondary-pink-text": PinkLightTwo,
      "--secondary-pink-background": PinkDarkTwo,
      "--tertiary-pink-text": PinkLightThree,
      "--tertiary-pink-background": PinkDarkThree,
      "--quaternary-pink-text": PinkLightFour,
      "--quaternary-pink-background": PinkDarkFour,
      "--quinary-pink-text": PinkLightFive,
      "--quinary-pink-background": PinkDarkFive,
      "--primary-grape-text": GrapeLightOne,
      "--primary-grape-background": GrapeDarkOne,
      "--secondary-grape-text": GrapeLightTwo,
      "--secondary-grape-background": GrapeDarkTwo,
      "--tertiary-grape-text": GrapeLightThree,
      "--tertiary-grape-background": GrapeDarkThree,
      "--quaternary-grape-text": GrapeLightFour,
      "--quaternary-grape-background": GrapeDarkFour,
      "--quinary-grape-text": GrapeLightFive,
      "--quinary-grape-background": GrapeDarkFive,
      "--primary-violet-text": VioletLightOne,
      "--primary-violet-background": VioletDarkOne,
      "--secondary-violet-text": VioletLightTwo,
      "--secondary-violet-background": VioletDarkTwo,
      "--tertiary-violet-text": VioletLightThree,
      "--tertiary-violet-background": VioletDarkThree,
      "--quaternary-violet-text": VioletLightFour,
      "--quaternary-violet-background": VioletDarkFour,
      "--quinary-violet-text": VioletLightFive,
      "--quinary-violet-background": VioletDarkFive,
      "--primary-indigo-text": IndigoLightOne,
      "--primary-indigo-background": IndigoDarkOne,
      "--secondary-indigo-text": IndigoLightTwo,
      "--secondary-indigo-background": IndigoDarkTwo,
      "--tertiary-indigo-text": IndigoLightThree,
      "--tertiary-indigo-background": IndigoDarkThree,
      "--quaternary-indigo-text": IndigoLightFour,
      "--quaternary-indigo-background": IndigoDarkFour,
      "--quinary-indigo-text": IndigoLightFive,
      "--quinary-indigo-background": IndigoDarkFive,
      "--primary-blue-text": BlueLightOne,
      "--primary-blue-background": BlueDarkOne,
      "--secondary-blue-text": BlueLightTwo,
      "--secondary-blue-background": BlueDarkTwo,
      "--tertiary-blue-text": BlueLightThree,
      "--tertiary-blue-background": BlueDarkThree,
      "--quaternary-blue-text": BlueLightFour,
      "--quaternary-blue-background": BlueDarkFour,
      "--quinary-blue-text": BlueLightFive,
      "--quinary-blue-background": BlueDarkFive,
      "--primary-cyan-text": CyanLightOne,
      "--primary-cyan-background": CyanDarkOne,
      "--secondary-cyan-text": CyanLightTwo,
      "--secondary-cyan-background": CyanDarkTwo,
      "--tertiary-cyan-text": CyanLightThree,
      "--tertiary-cyan-background": CyanDarkThree,
      "--quaternary-cyan-text": CyanLightFour,
      "--quaternary-cyan-background": CyanDarkFour,
      "--quinary-cyan-text": CyanLightFive,
      "--quinary-cyan-background": CyanDarkFive,
      "--primary-teal-text": TealLightOne,
      "--primary-teal-background": TealDarkOne,
      "--secondary-teal-text": TealLightTwo,
      "--secondary-teal-background": TealDarkTwo,
      "--tertiary-teal-text": TealLightThree,
      "--tertiary-teal-background": TealDarkThree,
      "--quaternary-teal-text": TealLightFour,
      "--quaternary-teal-background": TealDarkFour,
      "--quinary-teal-text": TealLightFive,
      "--quinary-teal-background": TealDarkFive,
      "--primary-green-text": GreenLightOne,
      "--primary-green-background": GreenDarkOne,
      "--secondary-green-text": GreenLightTwo,
      "--secondary-green-background": GreenDarkTwo,
      "--tertiary-green-text": GreenLightThree,
      "--tertiary-green-background": GreenDarkThree,
      "--quaternary-green-text": GreenLightFour,
      "--quaternary-green-background": GreenDarkFour,
      "--quinary-green-text": GreenLightFive,
      "--quinary-green-background": GreenDarkFive,
      "--primary-lime-text": LimeLightOne,
      "--primary-lime-background": LimeDarkOne,
      "--secondary-lime-text": LimeLightTwo,
      "--secondary-lime-background": LimeDarkTwo,
      "--tertiary-lime-text": LimeLightThree,
      "--tertiary-lime-background": LimeDarkThree,
      "--quaternary-lime-text": LimeLightFour,
      "--quaternary-lime-background": LimeDarkFour,
      "--quinary-lime-text": LimeLightFive,
      "--quinary-lime-background": LimeDarkFive,
      "--primary-yellow-text": YellowLightOne,
      "--primary-yellow-background": YellowDarkOne,
      "--secondary-yellow-text": YellowLightTwo,
      "--secondary-yellow-background": YellowDarkTwo,
      "--tertiary-yellow-text": YellowLightThree,
      "--tertiary-yellow-background": YellowDarkThree,
      "--quaternary-yellow-text": YellowLightFour,
      "--quaternary-yellow-background": YellowDarkFour,
      "--quinary-yellow-text": YellowLightFive,
      "--quinary-yellow-background": YellowDarkFive,
      "--primary-orange-text": OrangeLightOne,
      "--primary-orange-background": OrangeDarkOne,
      "--secondary-orange-text": OrangeLightTwo,
      "--secondary-orange-background": OrangeDarkTwo,
      "--tertiary-orange-text": OrangeLightThree,
      "--tertiary-orange-background": OrangeDarkThree,
      "--quaternary-orange-text": OrangeLightFour,
      "--quaternary-orange-background": OrangeDarkFour,
      "--quinary-orange-text": OrangeLightFive,
      "--quinary-orange-background": OrangeDarkFive,
      "--theme-default-bg": DefaultDarkFive,
      "--theme-red-bg": RedDarkFive,
      "--theme-pink-bg": PinkDarkFive,
      "--theme-grape-bg": GrapeDarkFive,
      "--theme-violet-bg": VioletDarkFive,
      "--theme-indigo-bg": IndigoDarkFive,
      "--theme-blue-bg": BlueDarkFive,
      "--theme-cyan-bg": CyanDarkFive,
      "--theme-teal-bg": TealDarkFive,
      "--theme-green-bg": GreenDarkFive,
      "--theme-lime-bg": LimeDarkFive,
      "--theme-yellow-bg": YellowDarkFive,
      "--theme-orange-bg": OrangeDarkFive,
    },
  };
};
