export enum Preset {
  "Original" = "original",
  "Instagram Square" = "instagram_square",
  "Instagram Portrait" = "instagram_portrait",
  "Instagram Landscape" = "instagram_landscape",
  "Instagram Story" = "instagram_story",
  "Facebook Post" = "facebook_post",
  "Facebook Story" = "facebook_story",
  "Facebook Cover" = "facebook_cover",
  "Twitter Post" = "twitter_post",
  "Twitter Banner" = "twitter_banner",
  "Threads Post" = "threads_post",
  "LinkedIn Post" = "linkedin_post",
  "LinkedIn Banner" = "linkedin_banner",
  "Pinterest Standard" = "pinterest_standard",
  "Pinterest Square" = "pinterest_square",
  "Snapchat Story" = "snapchat_story",
  "YouTube Thumbnail" = "youtube_thumbnail",
  "YouTube Banner" = "youtube_banner",
  "TikTok Story" = "tiktok_story",
  "Reddit Post" = "reddit_post",
  "Twitch Banner" = "twitch_banner",
  "Medium Featured" = "medium_featured",
  "WhatsApp Status" = "whatsapp_status",
}
