export enum Preset {
  "Original" = "original",
  "Facebook Shared Link" = "facebook_shared_link",
  "Facebook Cover" = "facebook_cover",
  "Facebook Stories" = "facebook_stories",
  "Facebook Vertical Portrait" = "facebook_vertical_portrait",
  "Facebook Multiple Images" = "facebook_multiple_images",
  "Instagram Square" = "instagram_square",
  "Instagram Portrait" = "instagram_portrait",
  "Instagram Landscape" = "instagram_landscape",
  "Instagram Stories" = "instagram_stories",
  "LinkedIn Square" = "linkedin_square",
  "LinkedIn Landscape" = "linkedin_landscape",
  "LinkedIn Portrait" = "linkedin_portrait",
  "LinkedIn Carousel" = "linkedin_carousel",
  "Threads" = "threads",
  "Bluesky" = "bluesky",
  "X Landscape" = "x_landscape",
  "X Portrait" = "x_portrait",
  "X Square" = "x_square",
  "X Header" = "x_header",
  "YouTube" = "youtube",
  "TikTok" = "tiktok",
  "Mastodon" = "mastodon",
  "Pinterest" = "pinterest",
}
