export enum Color {
  "Default" = "Default",
  "Red" = "Red",
  "Pink" = "Pink",
  "Grape" = "Grape",
  "Violet" = "Violet",
  "Indigo" = "Indigo",
  "Blue" = "Blue",
  "Cyan" = "Cyan",
  "Teal" = "Teal",
  "Green" = "Green",
  "Lime" = "Lime",
  "Yellow" = "Yellow",
  "Orange" = "Orange",
}
